// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV4XmYXY9rGHvNoRZpvjt2gvqEbTkC_pE',
    appId: '1:811614533419:web:891b2d213ddc2a6fb8776e',
    messagingSenderId: '811614533419',
    projectId: 'pendor-dc2ab',
    authDomain: 'pendor-dc2ab.firebaseapp.com',
    storageBucket: 'pendor-dc2ab.firebasestorage.app',
    measurementId: 'G-R7K6KSRCFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK43IzUcU3BLJeDxRw25ZJz5yeB7yzDWw',
    appId: '1:811614533419:android:60649c5d0a7af50cb8776e',
    messagingSenderId: '811614533419',
    projectId: 'pendor-dc2ab',
    storageBucket: 'pendor-dc2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5OVRdmFD1xI_9TnYBm2AQ4nsYAmv1E5I',
    appId: '1:811614533419:ios:a44a25e7744e23bfb8776e',
    messagingSenderId: '811614533419',
    projectId: 'pendor-dc2ab',
    storageBucket: 'pendor-dc2ab.firebasestorage.app',
    iosBundleId: 'com.example.pendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5OVRdmFD1xI_9TnYBm2AQ4nsYAmv1E5I',
    appId: '1:811614533419:ios:a44a25e7744e23bfb8776e',
    messagingSenderId: '811614533419',
    projectId: 'pendor-dc2ab',
    storageBucket: 'pendor-dc2ab.firebasestorage.app',
    iosBundleId: 'com.example.pendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV4XmYXY9rGHvNoRZpvjt2gvqEbTkC_pE',
    appId: '1:811614533419:web:558b51398277657fb8776e',
    messagingSenderId: '811614533419',
    projectId: 'pendor-dc2ab',
    authDomain: 'pendor-dc2ab.firebaseapp.com',
    storageBucket: 'pendor-dc2ab.firebasestorage.app',
    measurementId: 'G-7FNE7TT8HW',
  );
}
